name: Build

on:
  push:
    branches: [main]

jobs: 
  Protect:
    runs-on: ubuntu-latest
    steps:
    - name: Arborist
      id: arborist
      uses: term-world/arborist@v0.1.5
      with:
        branches: '["main"]'
        min-approvals: 2
        enforce-admins: true
        force-protect: true
    env:
      GITHUB_TOKEN: ${{ secrets.ARBORIST }}
  build-full-node:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          cd images/full-node
          docker build -f Dockerfile . -t chompchain-full:latest --build-arg="TXPOOL=mempool"
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Publish image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/chompchain-full
          docker tag chompchain-full:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
